---
book_repo: pivotal-cf/docs-book-rabbitmq-replicator
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

# cross-product resources
- repository:
    name: pivotal-cf/docs-on-demand-service-broker
    ref: v0.17.x
  directory: rabbitmq-replicator/odb
  no_docs: true

- repository:
    name: pivotal-cf/docs-rabbitmq-replicator
    ref: 'master'
  directory: rabbitmq-replicator
  subnav_template: rabbitmq-replicator_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.0
    local_header_img: /images/cloud_rings.png
    local_header_title: RabbitMQ for PCF Replicator
    search_placeholder: Search RabbitMQ Replicator
    url_prefix: rabbitmq-replicator
    local_product_version: 1.0
    local_header_links: []
    local_header_version_list:
